var routeAstopNames = ["Morewood Gardens Turn-around", "
Forbes and South Craig", "
South Dithridge at Wiinthrop Street", "
North Dithridge at Fifth Avenue", "
North Dithridge Street at Bayard Street ", "
North Dithridge Street at Centre Avenue", "
Centre Avenue at Melwood Avenue", "
Centre Avenue at North Neville Street", "
Centre Avenue at Devonshire Street", "
Centre Avenue at Morewood Avenue", "
Centre Avenue at Cypress Street", "
Centre Avenue at South Aiken Avenue", "
Centre Avenue at South Negley Avenue", "
South Negley Avenue at Ellsworth Avenue", "
South Negley Avenue at Elmer Street", "
South Negley Avenue at Walnut Street", "
South Negley Avenue at Howe Street", "
South Negley Avenue at Fifth Avenue", "
Fifth Avenue at Bellfonte Street", "
Fifth Avenue at South Aiken Avenue", "
Fifth Avenue at Wilkins Avenue"];

var routeBstopNames = ["Morewood Gardens Turn-around", "
Fifth Avenue at Wilkins Avenue", "
Fifth Avenue at South Aiken Avenue", "
Fifth Avenue at Bellefonte Street", "
South Negley at Howe Street", "
South Negley Avenue at Walnut Street", "
South Negely Avenue and Elmer Street", "
South Negely Avenue at Ellsworth Avenue", "
South Negley Avenue at East Busway", "
Centre Avenue at South Euclid Avenue", "
Penn Circle South at Trade Street", "
Penn Circle South at Shakespeare Street", "
Shady Avenue at Marchand Street", "
Shady Avenue at Walnut Street", "
Shady Avenue at Howe Street", "
Shady Avenue at Fifth Avenue", "
Fifth Avenue at Emerson Street", "
Fifth Avenue at South Highland Avenue", "
Fifth Avenue at College Street", "
Fifth Avenue at Maryland Avenue"];

var routeABstopNames = ["Morewood Gardens Turn-around", "
Forbes Avenue at South Craig Street", "
South Dithridge Street at Winthrop Street", "
North Dithridge Street at Fifth Avenue", "
North Dithridge Street at Bayard Street ", "
North Dithridge Street at Centre Avenue", "
Centre Avenue at Melwood Avenue", "
Centre Avenue at North Neville Street", "
Centre Avenue at Devonshire Street", "
Centre Avenue at Morewood Avenue", "
Centre Avenue and Cypress Street", "
Centre Avenue at South Aiken Avenue", "
Ellsworth Avenue at Bellfonte Street", "
Ellsworth Avenue at Ivy Street", "
Ellsworth Avenue and South Negley Avenue", "
South Negley Avenue at East Busway", "
Centre Avenue at South Euclid Avenue", "
Penn Circle South at Trade Street", "
Penn Circle South at Shakespeare Street", "
Shady Avenue at Marchland Street", "
Shady Avenue at Walnut Street", "
Shady Avenue at Howe Street", "
Shady Avenue at Fifth Avenue", "
Fifth Avenue at South Highland Avenue", "
Fifth Avenue at College Street", "
Fifth Avenue at Maryland Avenue", "
Fifth Avenue at South Negley Avenue ", "
Fifth Avenue at Bellefonte Street", "
Fifth Avenue at South Aiken Avenue", "
Fifth Avenue at Wilkins Avenue"];

var routeCstopNames = ["Morewood Gardens Turn-around", "
Fifth Avenue at North Neville Street", "
South Craig Street and Winthrop Street", "
Forbes Avenue (Hamburg Hall)", "
Forbes Avenue (University Center)", "
Forbes Avenue at Margaret Morrison Street", "
Forbes Avenue at Wightman Street", "
Wightman Street at Bartlett Street", "
Wightman Street at Beacon Street", "
Wightman Street at Hobart Street", "
Wightman Street at Phillips Avenue", "
Wightman Street at Pocusset Street", "
Pocusset Street at Murray Avenue", "
Forward Avenue at Shady Avenue", "
Forward Avenue at Tilbury Avenue", "
Forward Avenue at Beechwood Blvd.", "
Beechwood Blvd. at Nicholson Street", "
Beechwood Blvd. at Phillips Avenue", "
Beechwood Blvd. at Douglas Street", "
Beechwood Blvd. at Darlington Road", "
Beechwood Blvd. at South Dallas Avenue", "
Beechwood Blvd. at Forbes Avenue", "
Beechwood Blvd. at Dalzell Place", "
Wilkins Avenue at Denniston Street", "
Wilkins Avenue at Shady Avenue", "
WIlkins Avenue at Murray Avenue", "
Wilkins Avenue at South Negley Avenue", "
Wilkins Avenue at Wightman Street", "
Wilkins Avenue at Bellerock Avenue", "
Wilkins Avenue at Fair Oaks Street", "
Beeler Street at Wilkins Avenue", "
Beeler Street at Beelermont Place", "
Beeler Street at Unger Lane"];

var bakerySquareLongstopNames = ["Forbes Avenue (CIC)", "
Bakery Square (Long Route)", "
University Center Turn-around", "
Wightman Street at Beacon Street", "
Beacon Street at Murray Avenue", "
Beacon Street at Shady Avenue", "
Shady Avenue at Fifth Avenue", "
Fifth Avenue at Beechwood Blvd.", "
Bakery Square (Google)", "
Shady Avenue at Marchland Street", "
Shady Avenue at Walnut Street", "
Shady Avenue at Howe Street", "
Shady Avenue at Fifth Avenue", "
Fifth Avenue at Emerson Street", "
Fifth Avenue at South Highland Avenue", "
Fifth Avenue at College Street", "
Fifth Avenu at Maryland Avenue", "
Fifth Avenue at South Negley Avenue", "
Fifth Avenue at South Aiken Avenue", "
Fifth Avenue at Wilkins Avenue", "
Bigelow Blvd. at Forbess Avenue"];

var bakerySquareShortstopNames = ["CIC", "
Bakery Square (Short Route)", "
University Center Turn-around", "
Fifth Avenue at Beechwood Blvd.", "
Bakery Square (Google)", "
Shady Avenue at Walnut Street", "
Shady Avenue at Howe Street", "
Shady Avenue at Fifth Avenue", "
Fifth Avenue at Emerson Street", "
Fifth Avenue at South Highland Avenue", "
Fifth Avenue at College Street", "
Fifth Avenue at Maryland Avenue", "
Fifth Avenue at South Negley Avenue", "
Fifth Avenue at South Negely Avenue", "
Fifth Avenue at Wilkins Avenue", "
Bigelow Blvd. at Forbes Avenue"];

var PTCstopNames = ["Morewood Gardens Turn-around", "
Frew Street at Tech Street", "
Frew Street (Porter Hall)", "
PTC-Pittsburgh Technology Center"];

var escortstopNames = ["Frew Street (Porter Hall)", "
Morewood E-Tower (Rear)", "
Forbes Avenue (Hamburg Hall)", "
Forbes Avenue (University Center)", "
Margaret Morrison Plaza", "
Tech Street and Frew Street (Tepper)", "
South Dithridge at Winthrop Street", "
4616 Henry Street (INI)", "
300 South Craig Street"];
